In [1]:
import dask
import dask.dataframe as dd

In [2]:
from dask.distributed import LocalCluster
cluster = LocalCluster()
client = cluster.get_client()

In [4]:
train = dd.read_csv("data/training_set_VU_DM.csv")
imputed_train = dd.read_csv("midas_imp_1.csv")
# train["date_time"] = dd.to_datetime(train["date_time"], format= "%Y-%m-%d %H:%M:%S")

# test = dd.read_csv("data/test_set_VU_DM.csv")
# test["date_time"] = dd.to_datetime(test["date_time"], format= "%Y-%m-%d %H:%M:%S")
train.head(10)

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
0,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,893,3,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
1,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,10404,4,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
2,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,21315,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
3,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,27348,2,4.0,...,NaN,NaN,NaN,NaN,-1.0,0.0,5.0,0,NaN,0
4,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,29604,4,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
5,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,30184,4,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,7.0,0,NaN,0
6,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,44147,3,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
7,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,50984,2,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
8,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,53341,4,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,6.0,0,NaN,0
9,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,56880,4,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0

In [5]:
imputed_train.head(10)

,srch_id,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
0,1,12,187,172.635742,460.701660,219,893,3,3.5,1,...,-59.002941,57.864582,-46.839123,-49.256096,0.000000,0.000000,66.545067,0,259.568420,0
1,1,12,187,133.736481,384.395844,219,10404,4,4.0,1,...,-72.256927,65.220062,-58.179649,-52.799446,0.000000,0.000000,76.403618,0,512.676636,0
2,1,12,187,98.238007,362.777161,219,21315,3,4.5,1,...,15.844050,58.369648,9.252573,-39.987877,0.000000,0.000000,52.202633,0,303.015686,0
3,1,12,187,69.213814,294.346802,219,27348,2,4.0,1,...,150.079559,-47.143303,36.293537,-110.501541,-1.000000,0.000000,5.000000,0,-1.702711,0
4,1,12,187,130.796432,180.045914,219,29604,4,3.5,1,...,15.734169,60.182346,-24.765963,-99.623138,0.000000,0.000000,3.080381,0,395.297913,0
5,1,12,187,104.523201,277.827271,219,30184,4,4.5,1,...,53.411388,17.712030,-20.018614,-89.610512,0.000000,0.000000,7.000000,0,102.450928,0
6,1,12,187,63.918903,166.167770,219,44147,3,3.5,1,...,60.545483,129.932922,12.253237,-106.078049,0.000000,0.000000,37.725185,0,348.930786,0
7,1,12,187,145.065201,354.816711,219,50984,2,0.0,0,...,-31.874716,15.189915,-25.214682,-62.415943,3.048544,20.858345,77.026970,0,222.276047,0
8,1,12,187,41.634293,216.807983,219,53341,4,4.0,1,...,1.947731,15.605527,-3.571170,25.423109,0.000000,0.000000,6.000000,0,378.568359,0
9,1,12,187,119.038589,354.747925,219,56880,4,4.0,1,...,-20.634289,2.065374,-19.410105,46.983704,0.000000,0.000000,45.903713,0,353.212799,0

In [6]:
stats = imputed_train.describe().compute()

In [9]:
stats.to_clipboard(excel=True)

In [8]:
stats

,srch_id,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
count,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,...,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06,4.958347e+06
mean,1.663666e+05,9.953133e+00,1.753405e+02,7.398612e+01,1.902299e+02,1.739739e+02,7.007918e+04,3.180525e+00,3.759203e+00,6.346994e-01,...,3.984083e+01,3.470158e+01,-8.309417e+00,-1.009916e+01,1.017526e+01,7.370934e+00,1.895697e+01,4.474858e-02,2.820517e+02,2.791051e-02
std,9.611223e+04,7.646890e+00,6.591625e+01,1.585420e+02,6.163675e+03,6.834525e+01,4.060992e+04,1.051024e+00,1.220533e+00,4.815144e-01,...,4.715549e+02,6.719929e+01,5.316985e+01,6.230693e+02,1.755879e+01,1.756900e+01,3.861112e+02,2.067514e-01,8.670564e+03,1.647165e-01
min,1.000000e+00,1.000000e+00,1.000000e+00,-1.690415e+05,-7.768866e+06,1.000000e+00,1.000000e+00,0.000000e+00,-6.727355e+01,0.000000e+00,...,-6.137136e+05,-5.906682e+04,-1.470705e+04,-8.381044e+05,-3.563367e+03,-1.411772e+04,-2.920472e+05,0.000000e+00,-1.086503e+07,0.000000e+00
25%,8.095700e+04,5.000000e+00,1.030000e+02,4.530021e+01,1.585673e+02,1.060000e+02,3.546100e+04,3.000000e+00,3.500000e+00,0.000000e+00,...,-6.573473e+00,7.768979e+00,-1.113696e+01,-2.202293e+01,0.000000e+00,0.000000e+00,6.697434e+00,0.000000e+00,2.257095e+02,0.000000e+00
50%,1.645610e+05,5.000000e+00,2.190000e+02,8.659847e+01,2.134490e+02,2.190000e+02,7.012900e+04,3.000000e+00,4.000000e+00,1.000000e+00,...,6.020246e+01,4.126926e+01,9.496480e-01,1.121981e+01,6.959387e+00,4.121994e+00,2.400000e+01,0.000000e+00,2.949185e+02,0.000000e+00
75%,2.477710e+05,1.400000e+01,2.190000e+02,1.906209e+02,3.299125e+02,2.190000e+02,1.056120e+05,4.000000e+00,4.500000e+00,1.000000e+00,...,1.708659e+02,1.022263e+02,1.848533e+01,3.691886e+01,3.481832e+01,2.896563e+01,7.463520e+01,0.000000e+00,4.037567e+02,0.000000e+00
max,3.327850e+05,3.400000e+01,2.310000e+02,3.123388e+04,2.197989e+04,2.300000e+02,1.408210e+05,5.000000e+00,2.371630e+01,1.000000e+00,...,2.034923e+04,5.349264e+04,7.404469e+04,1.305421e+04,7.425688e+03,3.819593e+03,1.494000e+05,1.000000e+00,1.592924e+05,1.000000e+00

In [15]:
stats.shape

(8, 54)